## Import and load the data

In [2]:
import os
import glob
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import h5py

def get_dataset_name(file_name_with_dir):
    filename_without_dir = file_name_with_dir.split('/')[-1]
    temp = filename_without_dir.split('_')[:-1]
    dataset_name = "_".join(temp)
    return dataset_name

## Data visualisation

In [7]:
DATASET_PATH = "/Users/stijnroos/VisualStudio/DL_data/"

RAW_FOLDERS = {
    "intra_train": os.path.join(DATASET_PATH, "Intra", "train"),
    "intra_test": os.path.join(DATASET_PATH, "Intra", "test"),
    "cross_train": os.path.join(DATASET_PATH, "Cross", "train"),
    "cross_test1": os.path.join(DATASET_PATH, "Cross", "test1"),
    "cross_test2": os.path.join(DATASET_PATH, "Cross", "test2"),
    "cross_test3": os.path.join(DATASET_PATH, "Cross", "test3"),
}

def parse_filename(path):
    name = os.path.basename(path).replace(".h5", "")
    parts = name.split("_")
    subject = parts[-2]
    chunk = int(parts[-1])
    task = "_".join(parts[:-2])
    return task, subject, chunk

rows = []

for split_name, folder in RAW_FOLDERS.items():
    files = sorted(glob.glob(os.path.join(folder, "*.h5")))
    for file in files:
        task, subject, chunk = parse_filename(file)
        rows.append({
            "split": split_name,
            "file": os.path.basename(file),
            "task": task,
            "subject": subject,
            "chunk": chunk,
            "path": file
        })

df_files = pd.DataFrame(rows)
df_files.head(10)

,split,file,task,subject,chunk,path
0,intra_train,rest_105923_1.h5,rest,105923,1,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
1,intra_train,rest_105923_2.h5,rest,105923,2,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
2,intra_train,rest_105923_3.h5,rest,105923,3,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
3,intra_train,rest_105923_4.h5,rest,105923,4,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
4,intra_train,rest_105923_5.h5,rest,105923,5,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
5,intra_train,rest_105923_6.h5,rest,105923,6,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
6,intra_train,rest_105923_7.h5,rest,105923,7,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
7,intra_train,rest_105923_8.h5,rest,105923,8,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
8,intra_train,task_motor_105923_1.h5,task_motor,105923,1,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...
9,intra_train,task_motor_105923_2.h5,task_motor,105923,2,/Users/stijnroos/VisualStudio/DL_data/Intra/tr...

In [8]:
print("Total files:", len(df_files))
display(df_files.groupby(["split", "task"]).size().unstack(fill_value=0))
display(df_files.groupby(["split", "subject"]).size().unstack(fill_value=0))
display(df_files.groupby(["split", "task", "subject"]).size())

Total files: 152

task         rest  task_motor  task_story_math  task_working_memory
split
cross_test1     4           4                4                    4
cross_test2     4           4                4                    4
cross_test3     4           4                4                    4
cross_train    16          16               16                   16
intra_test      2           2                2                    2
intra_train     8           8                8                    8

subject      105923  113922  162935  164636  707749  725751  735148
split
cross_test1       0       0      16       0       0       0       0
cross_test2       0       0       0       0      16       0       0
cross_test3       0       0       0       0       0       8       8
cross_train       0      32       0      32       0       0       0
intra_test        8       0       0       0       0       0       0
intra_train      32       0       0       0       0       0       0

split        task                 subject
cross_test1  rest                 162935     4
             task_motor           162935     4
             task_story_math      162935     4
             task_working_memory  162935     4
cross_test2  rest                 707749     4
             task_motor           707749     4
             task_story_math      707749     4
             task_working_memory  707749     4
cross_test3  rest                 725751     2
                                  735148     2
             task_motor           725751     2
                                  735148     2
             task_story_math      725751     2
                                  735148     2
             task_working_memory  725751     2
                                  735148     2
cross_train  rest                 113922     8
                                  164636     8
             task_motor           113922     8
                                  164636     8
             task_story_math      113922     8
                                  164636     8
             task_working_memory  113922     8
                                  164636     8
intra_test   rest                 105923     2
             task_motor           105923     2
             task_story_math      105923     2
             task_working_memory  105923     2
intra_train  rest                 105923     8
             task_motor           105923     8
             task_story_math      105923     8
             task_working_memory  105923     8
dtype: int64